openapi: 3.0.0
info:
  title: Sari-Sari Store API
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
paths:
  /products/:
    get:
      summary: List products
      responses:
        '200': {description: OK}
    post:
      summary: Create a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201': {description: Created}
  /products/{id}/:
    get:
      summary: Retrieve a product
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: integer}
      responses:
        '200': {description: OK}
        '404': {description: Not found}
    put:
      summary: Update a product
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: integer}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200': {description: Updated}
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          schema: {type: integer}
      responses:
        '204': {description: Deleted}
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        sku:
          type: string
        price:
          type: number
        stock:
          type: integer
