name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: sari_store_db
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    env:
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: sari_store_db
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      VITE_API_URL: http://localhost:8000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt
      - name: Migrate database
        run: |
          cd backend
          python manage.py migrate
      - name: Run backend tests
        run: pytest -q
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install frontend deps
        run: |
          cd frontend
          npm ci
      - name: Build frontend
        run: |
          cd frontend
          npm run build
